- name: unregister iptables service
  service: name=iptables runlevel=no enabled=no

- name: stopping services
  service: name={{ item }} state=stopped
  with_items:
    - iptables

- name: copy epel.repo
  copy: src=etc/yum.repos.d/epel.repo dest=/etc/yum.repos.d/epel.repo

- name: copy rpm
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/usr/local/src/RPM-GPG-KEY-EPEL-6

- name: import rpm key
  rpm_key: key=/usr/local/src/RPM-GPG-KEY-EPEL-6 state=present

- name: installing packages with epel
  yum: name={{ item }} state=present enablerepo=epel
  with_items:
    - vim
    - curl
    - git
    - ntp
    - ntpdate
    - gcc
    - gcc-c++
    - zlib-devel
    - readline-devel
    - libcurl-devel
    - java-1.7.0-openjdk

- name: installing httpd
  yum: name={{ item }} state=present enablerepo=epel
  with_items:
    - httpd

- name: restarting the httpd
  service: name={{ item }} state=restarted
  with_items:
    - httpd
