- name: copy /usr/local/src/elasticsearch-*.*.*.noarch.rpm
  copy: src=usr/local/src/elasticsearch-1.3.2.noarch.rpm dest=/usr/local/src/elasticsearch-1.3.2.noarch.rpm

- name: installing elasticsearch
  yum: name=/usr/local/src/elasticsearch-1.3.2.noarch.rpm state=present

- name: installing plugins
  shell: >-
    bin/plugin -install {{ item }}
    chdir={{ es_home }}
  ignore_errors: yes
  with_items:
    - elasticsearch/elasticsearch-analysis-kuromoji/2.3.0
    - royrusso/elasticsearch-HQ
    - polyfractal/elasticsearch-inquisitor

- name: installing plugins from url
  shell: >-
    bin/plugin -url {{ item.url }} -install {{ item.name }}
    chdir={{ es_home }}
  ignore_errors: yes
  with_items:
    - {url: 'http://download.elasticsearch.org/kibana/kibana/kibana-latest.zip', name: 'elasticsearch/kibana3'}

- name: copy /etc/init.d/*
  template: src=etc/init.d/{{ item }} dest=/etc/init.d/{{ item }} owner=root group=root mode=0755
  with_items:
    - elasticsearch

- name: copy /etc/elasticsearch/*
  template: src=etc/elasticsearch/{{ item }} dest=/etc/elasticsearch/{{ item }} owner=root group=root mode=0644
  with_items:
    - elasticsearch.yml
    - logging.yml

- name: copy /etc/logrotate.d/*
  template: src=etc/logrotate.d/{{ item }} dest=/etc/logrotate.d/{{ item }} owner=root group=root mode=0644
  with_items:
    - elasticsearch

- name: copy /etc/sysconfig/*
  template: src=etc/sysconfig/{{ item }} dest=/etc/sysconfig/{{ item }} owner=root group=root mode=0644
  with_items:
    - elasticsearch

- name: restarting the elasticsearch
  service: name={{ item }} state=restarted
  with_items:
    - elasticsearch
